service: CatOps

package:
  exclude:
    - ./**
  include:
    - handler.py
    - plugins/**
    - catops/*

provider:
  name: aws
  runtime: python3.6
  profile: serverless

functions:
  dispatcher:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
